### ISSUE TITLE
Error loading coco files. 

### ISSUE THREAD

**Issue by makanju0la** [ysymyth/ec-nl#2]
Hi,

I am trying to replicate your codebase. The Readme instruction says we should put the files downloaded from the image_features google drive folder into `./ec-pretrain/data`. I created a directory called ec-pretrain/data and added the files there but whenever I run train.py for the for the Emergent Communication Game, I receive this error below:

_Entering Main
Traceback (most recent call last):
  File "train.py", line 73, in <module>
    data = torch.load(feat_path)
  File "/home/mogunleye/miniconda3/envs/ec-nl1/lib/python3.6/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/mogunleye/miniconda3/envs/ec-nl1/lib/python3.6/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/mogunleye/miniconda3/envs/ec-nl1/lib/python3.6/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './data/coco.pt'_

Then I thought maybe I should put the data in `./data/` instead of `./ec-pretrain/data` but I still get the same error. 

I was wondering if I have done something wrong? 

Thanks and looking forward to hearing from you.

**Comment by ysymyth** [comment]
Hi, please take a look at https://github.com/ysymyth/ec-nl#data and make sure you download data to the right location. Feel free to re-open if you have followup questions!
